version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-samples-rest-middy-modular"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-yh499vm6bu96"
s3_prefix = "sam-samples-rest-middy-modular"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
