AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  rest-middy-modular

  SAM Template for rest-middy-modular

Globals:
  Function:
    CodeUri: app/
    MemorySize: 128
    Runtime: nodejs16.x
    Timeout: 6
    Environment:
      Variables:
        SAMPLE_TABLE: !Ref SampleTable

Resources:
  ItemListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/items/list/index.handle
      Description: A simple example includes a HTTP get method to get all items from a DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET

  ItemFindFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/items/find/index.handle
      Description: A simple example includes a HTTP get method to get one item by id from a DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{itemId}
            Method: GET

  ItemCreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/items/create/index.handle
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST

  ItemUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/items/update/index.handle
      Description: A simple example includes a HTTP put method to update one item by id in a DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{itemId}
            Method: PUT

  ItemDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/items/delete/index.handle
      Description: A simple example includes a HTTP delete method to delete one item by id from a DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{itemId}
            Method: DELETE

  SampleTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

Outputs:
  ApiEndpoint:
    Description: 'API Gateway endpoint URL'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
